### ISSUE TITLE
Global CSS

### ISSUE THREAD

**Issue by ArgonAlex** [unicorn-standard/react-pacomo#10]
I love the idea of this package. It is sweet and simple, but there is one crucial piece of functionality that is missing. It would be great if there was a way to specify that a class should not be autoprefixed. This way we could use css classes that are defined globally. E.g. utility classes such as clearfix, Bootstrap classes.

One way I could think of doing this is prepending a class with some token that marks it as global:

``` jsx
<Navbar className="*navbar *navbar-default mynav" />
```

Which is output as:

``` html
<div className="navbar navbar-default app-Component-mynav">
   ...
</div>
```

**Comment by zapaiamarce** [comment]
+1

**Comment by jamesknelson** [comment]
@alexwalter88

Making react-pacomo not work interoperably with global classes was a design decision on my part. I think there are generally superior ways to accomplish the same thing. For example, instead of using a `navbar` class from bootstrap, I’d recommend creating a `Navbar` react component. If you'd like that component to use bootstrap styles, just don't use react-pacomo on that one component. You can do similar things for other bootstrap components like Button, Dropdown, etc. But it would be prettier if you just wrote them in pacomo ;)

react-pacomo isn't meant to be used on every component in a project - only where it makes sense. For example, I'll often manually add pacomo classes to a grid component for performance, or will write pacomo-free components when they're unstyled, or use legacy code (like bootstrap).
