### ISSUE TITLE
CSS Module cons

### ISSUE THREAD

**Issue by neverfox** [unicorn-standard/react-pacomo#9]
Very interesting project with a lot of inspiring ideas. However, and with all due respect, the cons about CSS Modules strike me as mostly unfair.
- Depends on a build system

Sure, but who is building any serious React app without one? In fact, you say in your article about inline styles, "But now that we all have access to wonderful tools like Webpack, this benefit isn’t limited to Inline Style anymore." If you have Webpack, you have CSS Modules. It's probably more accurate to say that it depends on Webpack, but if you're also encouraging Webpack use, I'm not sure who you're hoping to satisfy with this one.
- Does not handle props.className automatically
- Does not append a root class automatically
- Does not handle classnames objects

Okay, but that's apples and oranges isn't it? You cannot really compare vanilla CSS Modules (really just the implementation of a spec; it's not itself claiming to be a full-fledged React library) to something like this that gets all of those features from a decorator. Pacomo spec CSS files would no more bring these features to your app if you merely imported them either. And nothing really prevents similar decorators from being written for CSS Modules, and in fact those do exist, e.g. react-css-modules. Comparing react-pacomo to _those_ would seem like a better comparison, and hopefully good ideas would become infectious and improve everyone's respective decorator implementations.
- You don't know your class names ahead of time, meaning no monkey-patching

This one has teeth, I think. I'm still trying to understand what the best practices are in the CSS Module world for overriding styles, but I imagine you could do a couple of things:
- Offer an API on your component that takes inline styles and use them for overrides (since they will have higher specificity
- Offer an API on your component that takes a CSS module and `Object.assign` it to the internal one.

I hope you will take my comments in a helpful light and consider revising or discussing more some of these things so users will have a fair comparison when deciding what to pick for their next project.

**Comment by jamesknelson** [comment]
@neverfox I've done a bit of thinking since initially writing and blogging about react-pacomo, and have actually come to the conclusion that CSS Modules solve a number of cases better than react-pacomo (but not all of them).

I'm half way through writing this up, but between starting 2 new jobs and moving twice, it is taking a little longer than I'd planned. This gist is that if you need performance or are writing a complex app, CSS Modules are a better pick, while if you're writing a library react-pacomo may be better.

I'll close this comment for now, but hope to get an updated comparison up sooner rather than later.
